name: Sync Fork

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: pcm-dpc
          base: master
          head: master
          auto_approve: true
          auto_merge: true
          ignore_fail: true
