name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '30 18 * * *'
    # scheduled for 00:00 every Monday

jobs:  
  merge-dpc-COVID-19:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: pcm-dpc/COVID-19      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master          # set the branch to merge to
