name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '30 18 * * *'
    # scheduled for 00:00 every Monday

jobs:
  merge-COVID-19-from-dpc:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: pcm-dpc/COVID-19
          upstream-branch: master   
          branch: master          
